### ISSUE TITLE
As if there is a mistake in function of gen_sample for Beam Search engine 

### ISSUE THREAD

**Issue by zhaoluffy** [yaoli/arctic-capgen-vid#14]
![mistake](https://cloud.githubusercontent.com/assets/16127165/20737011/24e5f166-b6e5-11e6-8d50-ca7e340f4412.png)
I use your code to set up my own framework, I find this is mistake is shown in attach file. When I change the 'ti' to 'idx', The result is better than the result you reported.

**Comment by yaoli** [comment]
You are right and the results should be better.
