### ISSUE TITLE
train, valid and test splits

### ISSUE THREAD

**Issue by zhuolinumd** [yaoli/arctic-capgen-vid#17]
Hi @yaoli , In the pre-processing data file, the video names have been rename as vid***. Can you share the youtube video-id mapping (original youtube video name->vid***) with me? 
I want to use your split setting in my experiments.  I want to re-extract features from videos in the Youtube2Text dataset. Thank you!

**Comment by yaoli** [comment]
https://github.com/yaoli/arctic-capgen-vid/blob/master/youtube_mapping.txt
