### ISSUE TITLE
import tables

### ISSUE THREAD

**Issue by MichaelXin** [yaoli/arctic-capgen-vid#4]
Hi Dr. Yao,
    When I test the data_engine.py, it gives me an error that "ImportError: No module named tables".
    Could you tell me where this module is?
    Thank you so much!

**Comment by ghost** [comment]
Hi Yao
I met the same problem. Is that means I have to install pytable?
Thanks a lot!

**Comment by yaoli** [comment]
I believe it's this package that you need http://www.pytables.org/

**Comment by ghost** [comment]
Thanks a lot! I will have a try!

**Comment by MichaelXin** [comment]
OK, it works! Thank you very much!
